### ISSUE TITLE
Icons don't show up

### ISSUE THREAD

**Issue by echolock** [DominikLingenover/DMNK-Tools#5]
![hindie_MSqgDwGdbo](https://user-images.githubusercontent.com/17464684/97901000-88163500-1d09-11eb-9d86-934028e096d8.png)

Also fSpy shelf tool isn't included, but is referenced in the shelf set.

**Comment by DominikLingenover** [comment]
Hey,

did you download from the "Releases" section or did you clone the repository? The releases are outdated and you should clone the repository instead.

**Comment by echolock** [comment]
Ahh! Thanks Dominik, it's working now!
